# Generated by Django 5.2.7 on 2025-11-22 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('nue', 'Nuevo'), ('pro', 'En proceso'), ('fin', 'Finalizado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('appat', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apmat', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('nombre_usuario', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('contrasenia', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['appat', 'apmat', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=100)),
                ('descripcion_tarea', models.TextField(max_length=500)),
                ('asignatura', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('prioridad', models.CharField(choices=[('alt', 'Alta'), ('med', 'Media'), ('baj', 'Baja')], default='med', max_length=10)),
                ('modalidad', models.CharField(choices=[('ind', 'Individual'), ('grup', 'En Grupo')], default='ind', max_length=15)),
                ('estatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='miapp.estatu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha_entrega', 'prioridad'],
            },
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
