# Generated by Django 5.2.8 on 2025-11-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_estatu_usuario_remove_estudiante_carrera_tarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_entrega',
            field=models.DateField(),
        ),
    ]
