# Generated by Django 5.2.7 on 2025-10-27 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=15)),
                ('modalidad', models.CharField(choices=[('pre', 'Presencial'), ('mx', 'Mixta'), ('vr', 'Virtual')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('appat', models.CharField(max_length=20)),
                ('apmat', models.CharField(max_length=20)),
                ('matricula', models.CharField(max_length=9)),
                ('curp', models.CharField(max_length=20)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.carrera')),
            ],
        ),
    ]
