# Generated by Django 5.2.8 on 2025-12-07 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0003_alter_tarea_fecha_entrega"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComentarioTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gen", "General"),
                            ("seg", "Seguimiento"),
                            ("obs", "Observación"),
                            ("rec", "Recordatorio"),
                        ],
                        default="gen",
                        max_length=3,
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="miapp.tarea",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios_tareas",
                        to="miapp.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario de Tarea",
                "verbose_name_plural": "Comentarios de Tareas",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
